version: '3.6'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha13
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    command:
      - graphql-engine
      - serve
      - --enable-console
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  magnetar:
    # env_file:
    #   - ../../server/.env
    container_name: backend
    build: ../../server
    volumes:
    - /Users/conorburke/workspace/Magnetar/server:/usr/src/magnetar/server
    command: yarn dev
    working_dir: /usr/src/magnetar
    ports:
      - "7777:7777"
      - "3000:3000"
    # environment:
    #   POSTGRES_URI: postgres://admin:password@postgres:5432/magenetar
    #   REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis   
volumes:
  db_data:
  
